name: PHP Linting

jobs:
  phplint:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: PHP Lint 5.4
        uses: prestashop/github-action-php-lint/5.4@v1.1
        with:
          folder-to-exclude: "! -path \"./vendor/*\" ! -path \"./folder/excluded/*\""
      - name: PHP Lint 5.5
        uses: prestashop/github-action-php-lint/5.5@v1.1
        with:
          folder-to-exclude: "! -path \"./vendor/*\" ! -path \"./folder/excluded/*\""
      - name: PHP Lint 5.6
        uses: prestashop/github-action-php-lint/5.6@v1.1
        with:
          folder-to-exclude: "! -path \"./vendor/*\" ! -path \"./folder/excluded/*\""
      - name: PHP Lint 7.1
        uses: prestashop/github-action-php-lint/7.1@v1.1
        with:
          folder-to-exclude: "! -path \"./vendor/*\" ! -path \"./folder/excluded/*\""
      - name: PHP Lint 7.2
        uses: prestashop/github-action-php-lint/7.2@v1.1
        with:
          folder-to-exclude: "! -path \"./vendor/*\" ! -path \"./folder/excluded/*\""
      - name: PHP Lint 7.3
        uses: prestashop/github-action-php-lint/7.3@v1.1
        with:
          folder-to-exclude: "! -path \"./vendor/*\" ! -path \"./folder/excluded/*\""
      - name: PHP Lint 7.4
        uses: prestashop/github-action-php-lint/7.4@v1.1
        with:
          folder-to-exclude: "! -path \"./vendor/*\" ! -path \"./folder/excluded/*\""
      - name: PHP Lint 8.0
        uses: prestashop/github-action-php-lint/8.0@v1.1
        with:
          folder-to-exclude: "! -path \"./vendor/*\" ! -path \"./folder/excluded/*\""
      - name: PHP Lint 8.1
        uses: prestashop/github-action-php-lint/8.1@v1.1
        with:
          folder-to-exclude: "! -path \"./vendor/*\" ! -path \"./folder/excluded/*\""

on:
  push:
    branches:
      - main
      - stable
